name: React CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm

      # 3. Check versions
      - name: Check Node.js version
        run: |
          node -v
          npm -v

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Lint
      - name: Run lint
        run: npm run lint

      # 6. Tests
      - name: Run tests
        run: npm test

      # 7. Build
      - name: Build application
        run: npm run build

      # 8. Upload production build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/

  deploy:
    runs-on: ubuntu-latest

    # Deploy job starts only after build succeeds
    needs: build

    # This is important because our IAM trust policy
    # specifically trusts the "staging" GitHub environment.
    environment: staging

    steps:
      # 9. Configure AWS credentials using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::597787441762:role/S3StagingDeployment
          aws-region: ap-south-1
          role-session-name: GitHubActionsStagingDeploy

      # 10. Verify AWS authentication
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      # 11. Download the React build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      # 12. Inspect downloaded artifact
      - name: Inspect downloaded artifact
        run: |
          echo "Files downloaded:"
          ls -la

          echo "Contents:"
          find . -maxdepth 3 -type f